import type { GuideQuestionGroup } from './types'

/**
 * 110 questions across eight groups. Numbering is continuous across groups and
 * matches the source document — it is referenced from the cheat sheets, so don't
 * renumber when editing.
 */
export const QUESTION_GROUPS = [
  {
    id: 'openers',
    title: 'Openers',
    tierHint: '10',
    blurb: 'Low pressure, high yield.',
    questions: [
      { n: 1, q: '“How’s your week been — actually, not the polite version?”' },
      { n: 2, q: '“Have you been here before, or are we both taking a risk?”' },
      { n: 3, q: '“What did you do today before this?”' },
      { n: 4, q: '“Are you a ‘plans on a weeknight’ person, or was this a stretch?”' },
      { n: 5, q: '“How long have you been in [city]? Do you like it, or are you plotting an escape?”' },
      { n: 6, q: '“What’s the thing you’ve been most looking forward to lately?”' },
      {
        n: 7,
        q: '“I’m going to guess — you’re not from here originally.”',
        note: 'A light statement-guess is more fun than a question.',
      },
      { n: 8, q: '“What’s been taking up most of your brain lately?”' },
      { n: 9, q: '“Okay, real question: are you a morning person or do you just fake it?”' },
      { n: 10, q: '“What’s something you did recently that you’re weirdly proud of?”' },
    ],
  },
  {
    id: 'light-and-fun',
    title: 'Light and fun',
    tierHint: '20 · tier 2',
    blurb: 'The workhorses. Deploy anywhere after the first ten minutes.',
    questions: [
      { n: 11, q: '“What’s a completely irrational opinion you hold?”' },
      { n: 12, q: '“What’s the hill you’ll die on that nobody else cares about?”' },
      { n: 13, q: '“What’s a useless talent you have?”' },
      { n: 14, q: '“What’s the most overrated food? Be brave.”' },
      { n: 15, q: '“What did you want to be when you were ten?”' },
      { n: 16, q: '“What’s your most-used app that isn’t social media?”' },
      { n: 17, q: '“What’s the last thing that made you actually laugh out loud — not just exhale?”' },
      { n: 18, q: '“What’s something everyone loves that you just don’t get?”' },
      { n: 19, q: '“What would you do with a completely free Saturday — no obligations, no guilt?”' },
      { n: 20, q: '“What’s the worst haircut you’ve ever had?”' },
      { n: 21, q: '“What’s your comfort rewatch?”' },
      { n: 22, q: '“What’s the pettiest thing that ruins your day?”' },
      { n: 23, q: '“What are you unreasonably competitive about?”' },
      { n: 24, q: '“What’s the strangest job you’ve ever had?”' },
      {
        n: 25,
        q: '“If your last three purchases were the only evidence, what would someone conclude about you?”',
      },
      { n: 26, q: '“What’s something you were really into for exactly two months and then never again?”' },
      { n: 27, q: '“What’s the best money you’ve spent under fifty bucks?”' },
      { n: 28, q: '“What’s a food combination you like that other people find disgusting?”' },
      { n: 29, q: '“Who’s the most interesting person you’re related to?”' },
      { n: 30, q: '“What’s your dead-simple, non-negotiable Sunday ritual?”' },
    ],
  },
  {
    id: 'story-extractors',
    title: 'Story-extractors',
    tierHint: '20 · tier 2',
    blurb:
      'These ask for *a time when*, not *what kind of person are you.* Narrative questions get you three minutes of animated talking. Trait questions get you an adjective.',
    questions: [
      { n: 31, q: '“What’s the best trip you’ve ever taken? Not the nicest — the best.”' },
      { n: 32, q: '“Tell me about a time you were completely out of your depth.”' },
      { n: 33, q: '“What’s the most spontaneous thing you’ve ever actually gone through with?”' },
      { n: 34, q: '“What’s a decision you made that made no sense to anyone else at the time?”' },
      { n: 35, q: '“What’s the closest you’ve come to a genuine disaster?”' },
      { n: 36, q: '“Tell me about the worst job you ever had.”' },
      { n: 37, q: '“What’s the strangest place you’ve ever slept?”' },
      { n: 38, q: '“What’s the best thing a stranger has ever done for you?”' },
      { n: 39, q: '“Have you ever gotten seriously lost somewhere?”' },
      { n: 40, q: '“What’s a story your family tells about you that you’re tired of?”' },
      { n: 41, q: '“When’s the last time you were genuinely surprised by something?”' },
      { n: 42, q: '“What’s the most trouble you got into as a kid?”' },
      { n: 43, q: '“Tell me about a time you completely changed your mind about something.”' },
      { n: 44, q: '“What’s the best concert or show you’ve been to?”' },
      { n: 45, q: '“What’s something you tried once and immediately knew was not for you?”' },
      { n: 46, q: '“What’s the boldest thing you’ve ever said to someone?”' },
      { n: 47, q: '“What’s a risk you took that actually paid off?”' },
      { n: 48, q: '“Tell me about the last time you were really nervous.”' },
      { n: 49, q: '“What’s the most beautiful place you’ve ever been?”' },
      { n: 50, q: '“What’s a moment where you thought ‘my life is different now’?”' },
    ],
  },
  {
    id: 'values-and-direction',
    title: 'Values and direction',
    tierHint: '20 · tier 2→3',
    blurb: 'Back half of the date. Answer them yourself first.',
    questions: [
      { n: 51, q: '“What does a genuinely good week look like for you?”' },
      { n: 52, q: '“What are you working on that has nothing to do with your job?”' },
      { n: 53, q: '“What are you most proud of that isn’t on a résumé?”' },
      { n: 54, q: '“If you had a year off, fully funded, what would actually happen?”' },
      { n: 55, q: '“What’s something you’ve changed your mind about in the last few years?”' },
      { n: 56, q: '“Who’s someone you learned a lot from?”' },
      { n: 57, q: '“What do people usually get wrong about you at first?”' },
      {
        n: 58,
        q: '“Are you where you thought you’d be at this age?”',
        note: 'Handle gently — can land heavy.',
      },
      { n: 59, q: '“What’s something you want to be better at?”' },
      { n: 60, q: '“What do you do when things go badly? Like, what’s your actual pattern?”' },
      { n: 61, q: '“What kind of people do you want more of in your life?”' },
      { n: 62, q: '“What’s a boundary you’ve learned to hold?”' },
      { n: 63, q: '“What’s the best advice you’ve ever gotten and actually taken?”' },
      { n: 64, q: '“What matters more to you now than it did five years ago?”' },
      { n: 65, q: '“How do you know when you like someone?”' },
      {
        n: 66,
        q: '“What’s your relationship with your family like?”',
        note: 'Let her set the depth.',
      },
      { n: 67, q: '“What’s something you’d never compromise on?”' },
      { n: 68, q: '“What do you do that makes you lose track of time?”' },
      { n: 69, q: '“What’s the thing you’re most curious about right now?”' },
      { n: 70, q: '“If nothing you did mattered to your career, how would you spend your days?”' },
    ],
  },
  {
    id: 'deeper',
    title: 'Deeper',
    tierHint: '15 · tier 3',
    blurb: 'Late, selective, and only after you’ve gone first.',
    questions: [
      { n: 71, q: '“What’s something you’re still figuring out?”' },
      {
        n: 72,
        q: '“What’s the hardest thing you’ve been through that you’re willing to talk about?”',
        note: 'The second clause is doing important work — it gives her a graceful exit.',
      },
      { n: 73, q: '“What are you afraid of that you don’t usually admit?”' },
      { n: 74, q: '“What do you want your life to look like in five years — not career-wise, actually?”' },
      { n: 75, q: '“What’s a version of yourself you’ve had to let go of?”' },
      { n: 76, q: '“When do you feel most like yourself?”' },
      { n: 77, q: '“What’s something you’re grateful for that you don’t say out loud enough?”' },
      { n: 78, q: '“What’s the loneliest you’ve ever been?”' },
      { n: 79, q: '“What do you need from people close to you?”' },
      {
        n: 80,
        q: '“What did you learn from your last relationship?”',
        note: 'Only if she brings relationships up first.',
      },
      { n: 81, q: '“What’s a thing you believe that most people around you don’t?”' },
      { n: 82, q: '“What’s the kindest thing anyone’s done for you?”' },
      { n: 83, q: '“What would younger you think of you now?”' },
      { n: 84, q: '“What’s something you’d do if you weren’t scared of it?”' },
      { n: 85, q: '“What are you hoping for right now?”' },
    ],
  },
  {
    id: 'playful-and-flirty',
    title: 'Playful and flirty',
    tierHint: '15 · escalation notes',
    blurb:
      'Only once there’s warmth on the table — she’s laughing, engaged, reciprocating. Cold-flirting a stranger who hasn’t warmed up is the fastest way to shut a date down.',
    questions: [
      { n: 86, q: '“You’re trouble. I can already tell.”', note: 'Safe early, playful.' },
      {
        n: 87,
        q: '“That’s a controversial take. I’m going to need you to defend it.”',
        note: 'Safe anytime, great energy.',
      },
      {
        n: 88,
        q: '“Okay, I did not expect that from you.”',
        note: 'Signals she’s surprising you — a compliment.',
      },
      {
        n: 89,
        q: '“We’re going to have a problem, because [opposing preference].”',
        note: 'Mock conflict — very effective.',
      },
      { n: 90, q: '“You’ve clearly done this before.”', note: 'Mild, playful.' },
      {
        n: 91,
        q: '“How am I doing so far? Be honest.”',
        note: 'Only with real warmth already. Light is charming; anxious is needy.',
      },
      {
        n: 92,
        q: '“What’s the worst first date you’ve been on?”',
        note: 'Shared-conspiracy energy; makes this date the good one by contrast.',
      },
      {
        n: 93,
        q: '“You’re not what I expected.” → wait a beat → “In a good way.”',
        note: 'Classic for a reason.',
      },
      {
        n: 94,
        q: '“I’m just going to say it — this is going better than I planned for.”',
        note: 'Mid-late. Sincere flirting, very strong.',
      },
      {
        n: 95,
        q: '“What made you say yes to this?”',
        note: 'Mid-date, warm, genuinely interesting.',
      },
      { n: 96, q: '“You have a really good laugh.”', note: 'Specific, chosen-trait compliment.' },
      {
        n: 97,
        q: '“Are you always this [confident / funny / direct], or is this a performance for me?”',
        note: 'Needs a smile.',
      },
      { n: 98, q: '“I like how you think.”', note: 'Underused; lands hard when it’s true.' },
      {
        n: 99,
        q: '“That’s exactly the answer I was hoping you wouldn’t give.”',
        note: 'Mock disappointment.',
      },
      {
        n: 100,
        q: '“I’m having a really good time.”',
        note: 'The simplest, and honestly the most effective thing on this list.',
      },
    ],
  },
  {
    id: 'dating-specific',
    title: 'Dating-specific',
    tierHint: '10 · back half only',
    blurb:
      'Important, but badly timed by most people. **None of these belong in the first thirty minutes** — they convert a date into a screening interview. Save them for the back half, when there’s enough warmth that they read as curiosity rather than due diligence.',
    questions: [
      {
        n: 101,
        q: '“What are you actually looking for right now?”',
        note: 'The most important one. Around minute 60–90. Answer it yourself first, honestly.',
      },
      { n: 102, q: '“How long have you been on the apps?”' },
      {
        n: 103,
        q: '“How’s the dating scene been treating you?”',
        note: 'Light, funny, good rapport builder.',
      },
      {
        n: 104,
        q: '“What made you swipe on me?”',
        note: 'Playful, and genuinely useful information.',
      },
      { n: 105, q: '“What’s your deal-breaker?”' },
      {
        n: 106,
        q: '“Do you want kids?”',
        note: 'Legitimate — but at minute 15 it’s an interrogation.',
      },
      {
        n: 107,
        q: '“What’s the best date you’ve ever been on?”',
        note: 'Mines for what she actually enjoys. Useful for date two.',
      },
      {
        n: 108,
        q: '“Are you seeing other people right now?”',
        note: 'Neutral tone only. Information gathering, not a claim.',
      },
      { n: 109, q: '“How do you usually know when something’s not going to work?”' },
      {
        n: 110,
        q: '“What would make you want to see someone again?”',
        note: 'Playful and pointed at once.',
      },
    ],
  },
] as const satisfies readonly GuideQuestionGroup[]
