// 116 Date Ideas organized by setting type
// Each idea includes: title, description, category, setting_type, intensity_level,
// cost_level, estimated costs, duration, vibes, quick_filters, dietary info,
// search_keywords, venue_type, and reservation_platforms

export interface DateIdeaTemplate {
  title: string
  description: string
  category: string
  setting_type: 'big_city' | 'suburbs' | 'coastal' | 'mountain' | 'desert' | 'countryside' | 'tropical' | 'cold_weather' | 'indoor_only' | 'at_home' | null
  intensity_level: number
  cost_level: number
  estimated_cost_min: number | null
  estimated_cost_max: number | null
  duration_minutes: number
  vibe_tags: string[]
  quick_filters: string[]
  requires_reservation: boolean
  outdoor_only: boolean
  seasonal: string[] | null
  dietary_friendly: string[]
  search_keywords: string[]
  venue_type: string | null
  reservation_platforms: string[]
}

export const dateIdeas: DateIdeaTemplate[] = [
  // ============================================
  // BIG CITY (10 ideas)
  // ============================================
  {
    title: "Progressive Dinner Tour",
    description: "Start with appetizers at one spot, main course at another, and dessert at a third. Walk between restaurants while exploring different neighborhoods.",
    category: "restaurant",
    setting_type: "big_city",
    intensity_level: 2,
    cost_level: 3,
    estimated_cost_min: 100,
    estimated_cost_max: 200,
    duration_minutes: 240,
    vibe_tags: ["romantic", "foodie", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["progressive dinner", "multi-course dining", "restaurant hopping"],
    venue_type: "restaurant",
    reservation_platforms: ["opentable", "resy", "yelp"]
  },
  {
    title: "Chef's Counter Experience",
    description: "Book seats at a chef's counter or omakase bar for an intimate, interactive dining experience where you watch your meal being prepared.",
    category: "restaurant",
    setting_type: "big_city",
    intensity_level: 1,
    cost_level: 4,
    estimated_cost_min: 150,
    estimated_cost_max: 400,
    duration_minutes: 150,
    vibe_tags: ["romantic", "fancy", "foodie"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["omakase", "chef's counter", "tasting menu", "fine dining"],
    venue_type: "restaurant",
    reservation_platforms: ["resy", "opentable"]
  },
  {
    title: "Comedy Club + Late Night Dessert",
    description: "Catch a stand-up comedy show and then hit up a late-night dessert spot for pie, ice cream, or pastries while you recap the best jokes.",
    category: "entertainment",
    setting_type: "big_city",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 100,
    duration_minutes: 180,
    vibe_tags: ["fun", "social", "chill"],
    quick_filters: ["fun_silly"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "gluten-free"],
    search_keywords: ["comedy club", "stand-up comedy", "late night dessert"],
    venue_type: "entertainment",
    reservation_platforms: ["eventbrite", "yelp"]
  },
  {
    title: "Jazz Lounge Evening",
    description: "Find a dimly lit jazz club, order craft cocktails, and let the live music set the mood for deep conversation and connection.",
    category: "entertainment",
    setting_type: "big_city",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 100,
    duration_minutes: 180,
    vibe_tags: ["romantic", "chill", "fancy"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["jazz club", "live jazz", "cocktail lounge"],
    venue_type: "bar",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Museum After-Hours Event",
    description: "Many museums host special evening events with cocktails, DJ sets, and exclusive access. Experience art in a whole new way.",
    category: "cultural",
    setting_type: "big_city",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 180,
    vibe_tags: ["cultural", "fancy", "romantic"],
    quick_filters: ["intellectual"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["museum night", "after hours museum", "art event"],
    venue_type: "museum",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Food Hall Crawl",
    description: "Visit a trendy food hall and sample dishes from multiple vendors. Share bites, discover new cuisines, and people-watch together.",
    category: "restaurant",
    setting_type: "big_city",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["fun", "foodie", "chill"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["food hall", "food market", "street food"],
    venue_type: "restaurant",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Rooftop Views at Sunset",
    description: "Head to a rooftop bar or observation deck to watch the sunset paint the city skyline. Toast to each other as the city lights come alive.",
    category: "entertainment",
    setting_type: "big_city",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["romantic", "fancy", "chill"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["rooftop bar", "skyline view", "observation deck"],
    venue_type: "bar",
    reservation_platforms: ["yelp", "opentable"]
  },
  {
    title: "Live Theater Night",
    description: "Dress up for a night at the theater - whether it's Broadway, off-Broadway, or a local production. Dinner before or drinks after makes it complete.",
    category: "entertainment",
    setting_type: "big_city",
    intensity_level: 2,
    cost_level: 3,
    estimated_cost_min: 80,
    estimated_cost_max: 250,
    duration_minutes: 210,
    vibe_tags: ["fancy", "cultural", "romantic"],
    quick_filters: ["romantic", "intellectual"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["theater", "broadway", "live performance", "play"],
    venue_type: "theater",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "City Photo Scavenger Hunt",
    description: "Create a list of photo challenges (couple selfie with street art, at a famous landmark, etc.) and race through the city capturing memories.",
    category: "activity",
    setting_type: "big_city",
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 30,
    duration_minutes: 180,
    vibe_tags: ["adventurous", "fun", "active"],
    quick_filters: ["fun_silly", "active", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["photo walk", "scavenger hunt", "city exploration"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Late-Night Bookstore Browse",
    description: "Find a bookstore that stays open late. Browse together, pick books for each other, and end with coffee or tea at a nearby cafe.",
    category: "activity",
    setting_type: "big_city",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 60,
    duration_minutes: 120,
    vibe_tags: ["chill", "creative", "romantic"],
    quick_filters: ["intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["bookstore", "independent bookshop", "late night cafe"],
    venue_type: "retail",
    reservation_platforms: ["yelp", "google_maps"]
  },

  // ============================================
  // SUBURBS (10 ideas)
  // ============================================
  {
    title: "Bowling Night with a Wager",
    description: "Classic bowling with a twist - loser buys ice cream after! Keep score, talk trash playfully, and enjoy some retro fun.",
    category: "activity",
    setting_type: "suburbs",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 60,
    duration_minutes: 120,
    vibe_tags: ["fun", "active", "social"],
    quick_filters: ["fun_silly", "active"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["bowling alley", "bowling lanes"],
    venue_type: "entertainment",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Drive-In Movie Night",
    description: "Pack blankets and snacks, tune in on the radio, and enjoy a film under the stars from the comfort of your car.",
    category: "entertainment",
    setting_type: "suburbs",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 40,
    duration_minutes: 180,
    vibe_tags: ["romantic", "chill", "cozy"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["drive-in theater", "drive-in movie", "outdoor cinema"],
    venue_type: "entertainment",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Dessert First Date",
    description: "Skip dinner entirely and go straight for dessert! Try a bakery, ice cream parlor, or create your own dessert crawl.",
    category: "restaurant",
    setting_type: "suburbs",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 35,
    duration_minutes: 90,
    vibe_tags: ["fun", "chill", "foodie"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian"],
    search_keywords: ["bakery", "ice cream shop", "dessert cafe"],
    venue_type: "restaurant",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Local Diner Breakfast for Dinner",
    description: "Find a classic diner and order breakfast at 7pm. Pancakes, bacon, and milkshakes - comfort food at its finest.",
    category: "restaurant",
    setting_type: "suburbs",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 45,
    duration_minutes: 90,
    vibe_tags: ["cozy", "chill", "fun"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian"],
    search_keywords: ["diner", "breakfast restaurant", "24 hour diner"],
    venue_type: "restaurant",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Trivia Night at a Local Pub",
    description: "Team up for pub trivia! Put your combined knowledge to the test while enjoying drinks and bar snacks.",
    category: "entertainment",
    setting_type: "suburbs",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 25,
    estimated_cost_max: 50,
    duration_minutes: 150,
    vibe_tags: ["fun", "social", "chill"],
    quick_filters: ["fun_silly", "intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["trivia night", "pub quiz", "bar trivia"],
    venue_type: "bar",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Arcade Bar + Milkshakes",
    description: "Find a barcade or old-school arcade. Play classic games, challenge each other to air hockey, then cool down with milkshakes.",
    category: "entertainment",
    setting_type: "suburbs",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 60,
    duration_minutes: 150,
    vibe_tags: ["fun", "active", "social"],
    quick_filters: ["fun_silly", "active"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["arcade", "barcade", "game room"],
    venue_type: "entertainment",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Board Game Cafe Night",
    description: "Spend a cozy evening at a board game cafe. Pick from hundreds of games, sip coffee or tea, and get competitive (or cooperative!).",
    category: "activity",
    setting_type: "suburbs",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 40,
    duration_minutes: 180,
    vibe_tags: ["cozy", "fun", "chill"],
    quick_filters: ["fun_silly", "intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["board game cafe", "game cafe", "tabletop games"],
    venue_type: "cafe",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Mini Golf Challenge",
    description: "Hit the mini golf course for some friendly competition. Bonus points for themed courses with pirate ships or dinosaurs!",
    category: "activity",
    setting_type: "suburbs",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 40,
    duration_minutes: 90,
    vibe_tags: ["fun", "active", "social"],
    quick_filters: ["fun_silly", "active", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["mini golf", "putt putt", "miniature golf"],
    venue_type: "entertainment",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Community Event Discovery",
    description: "Check local event listings for a farmers market, craft fair, food truck rally, or community festival happening this weekend.",
    category: "activity",
    setting_type: "suburbs",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["social", "fun", "chill"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["farmers market", "community event", "local festival"],
    venue_type: null,
    reservation_platforms: ["eventbrite", "meetup", "google_maps"]
  },
  {
    title: "Sunset Picnic at the Park",
    description: "Pack a simple picnic basket and a blanket. Find a nice spot at a local park and watch the sunset while you eat and talk.",
    category: "outdoor",
    setting_type: "suburbs",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 40,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "relaxing"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["park", "picnic area", "sunset spot"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },

  // ============================================
  // COASTAL (10 ideas)
  // ============================================
  {
    title: "Sunset Beach Walk",
    description: "Time your visit for golden hour. Walk along the shoreline as the sun dips below the horizon, collecting shells and making memories.",
    category: "outdoor",
    setting_type: "coastal",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 10,
    duration_minutes: 90,
    vibe_tags: ["romantic", "relaxing", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["beach", "shoreline", "oceanfront"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Dockside Seafood Dinner",
    description: "Find a restaurant right on the water with fresh-catch specials. Watch the boats come in while you dine on the day's haul.",
    category: "restaurant",
    setting_type: "coastal",
    intensity_level: 1,
    cost_level: 3,
    estimated_cost_min: 80,
    estimated_cost_max: 150,
    duration_minutes: 120,
    vibe_tags: ["romantic", "foodie", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["waterfront dining", "seafood restaurant", "dockside restaurant"],
    venue_type: "restaurant",
    reservation_platforms: ["opentable", "resy", "yelp"]
  },
  {
    title: "Kayak at Golden Hour",
    description: "Rent tandem kayaks and paddle out as the sun sets. The calm water and changing colors create an unforgettable experience.",
    category: "activity",
    setting_type: "coastal",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["adventurous", "active", "romantic"],
    quick_filters: ["active", "romantic"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["kayak rental", "tandem kayak", "sunset kayaking"],
    venue_type: "outdoor",
    reservation_platforms: ["airbnb_experiences", "yelp", "google_maps"]
  },
  {
    title: "Fishing Trip + Snack Board",
    description: "Charter a fishing trip or rent rods at a pier. Even if you don't catch anything, bring a charcuterie board to enjoy while you wait.",
    category: "activity",
    setting_type: "coastal",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 150,
    duration_minutes: 240,
    vibe_tags: ["adventurous", "chill", "fun"],
    quick_filters: ["active"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["fishing charter", "pier fishing", "fishing trip"],
    venue_type: "outdoor",
    reservation_platforms: ["airbnb_experiences", "google_maps"]
  },
  {
    title: "Beach Bonfire + S'mores",
    description: "Check local regulations, then build a small bonfire on the beach. Roast marshmallows, make s'mores, and stargaze.",
    category: "outdoor",
    setting_type: "coastal",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 30,
    duration_minutes: 180,
    vibe_tags: ["romantic", "cozy", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian"],
    search_keywords: ["beach bonfire", "fire pit beach", "beach camping"],
    venue_type: null,
    reservation_platforms: ["recreation_gov", "google_maps"]
  },
  {
    title: "Seaside Breakfast",
    description: "Wake up early and find a beachside cafe for breakfast. Watch the morning light on the water while you enjoy coffee and pastries.",
    category: "restaurant",
    setting_type: "coastal",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 90,
    vibe_tags: ["chill", "romantic", "cozy"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["beach cafe", "oceanfront breakfast", "seaside brunch"],
    venue_type: "restaurant",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Lighthouse Photography Trip",
    description: "Visit a historic lighthouse and capture photos together. Many have small museums or tours that add to the adventure.",
    category: "activity",
    setting_type: "coastal",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 25,
    duration_minutes: 150,
    vibe_tags: ["adventurous", "cultural", "romantic"],
    quick_filters: ["intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["lighthouse", "lighthouse tour", "coastal landmark"],
    venue_type: null,
    reservation_platforms: ["nps", "google_maps"]
  },
  {
    title: "Harbor Boat Tour",
    description: "Take a boat tour of the harbor or coastline. Enjoy the sea breeze and learn about the area's maritime history.",
    category: "activity",
    setting_type: "coastal",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "cultural"],
    quick_filters: ["romantic"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["harbor cruise", "boat tour", "scenic cruise"],
    venue_type: "tour",
    reservation_platforms: ["airbnb_experiences", "yelp", "google_maps"]
  },
  {
    title: "Aquarium Date",
    description: "Spend a few hours exploring an aquarium. Watch the jellyfish, find Nemo, and don't skip the touch tanks!",
    category: "cultural",
    setting_type: "coastal",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 180,
    vibe_tags: ["fun", "cultural", "chill"],
    quick_filters: ["intellectual"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["aquarium", "sea life center", "ocean exhibit"],
    venue_type: "museum",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Waterfront Live Music",
    description: "Find a beachside bar or restaurant with live music. Enjoy the ocean breeze, good tunes, and each other's company.",
    category: "entertainment",
    setting_type: "coastal",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 70,
    duration_minutes: 180,
    vibe_tags: ["chill", "social", "romantic"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["beach bar", "waterfront music", "live music venue"],
    venue_type: "bar",
    reservation_platforms: ["yelp", "google_maps"]
  },

  // ============================================
  // MOUNTAIN (10 ideas)
  // ============================================
  {
    title: "Cabin Weekend Getaway",
    description: "Book a cozy cabin for the weekend. Disconnect from the world, build fires, cook together, and enjoy mountain views.",
    category: "activity",
    setting_type: "mountain",
    intensity_level: 4,
    cost_level: 3,
    estimated_cost_min: 150,
    estimated_cost_max: 400,
    duration_minutes: 2880,
    vibe_tags: ["romantic", "cozy", "adventurous"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["cabin rental", "mountain cabin", "weekend getaway"],
    venue_type: "lodging",
    reservation_platforms: ["airbnb_experiences", "recreation_gov"]
  },
  {
    title: "Scenic Drive + Vista Stops",
    description: "Take a winding mountain road with planned stops at overlooks and viewpoints. Pack snacks and make it a leisurely adventure.",
    category: "outdoor",
    setting_type: "mountain",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 40,
    duration_minutes: 240,
    vibe_tags: ["romantic", "adventurous", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["scenic drive", "mountain overlook", "vista point"],
    venue_type: null,
    reservation_platforms: ["nps", "google_maps"]
  },
  {
    title: "Natural Hot Springs Soak",
    description: "Find natural hot springs in the mountains. Soak in the warm mineral water surrounded by forest and fresh mountain air.",
    category: "relaxation",
    setting_type: "mountain",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 20,
    estimated_cost_max: 80,
    duration_minutes: 180,
    vibe_tags: ["romantic", "relaxing", "adventurous"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["hot springs", "natural springs", "mineral springs"],
    venue_type: "spa",
    reservation_platforms: ["recreation_gov", "google_maps"]
  },
  {
    title: "Night Skiing or Tubing",
    description: "Hit the slopes after dark for night skiing or snow tubing. The lit-up runs and fewer crowds make it magical.",
    category: "activity",
    setting_type: "mountain",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 120,
    duration_minutes: 180,
    vibe_tags: ["adventurous", "active", "fun"],
    quick_filters: ["active", "fun_silly"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["night skiing", "snow tubing", "ski resort"],
    venue_type: "outdoor",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Sunset Summit Hike",
    description: "Time a moderate hike to reach a summit right at sunset. Bring headlamps for the descent and a thermos of hot cocoa.",
    category: "outdoor",
    setting_type: "mountain",
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 20,
    duration_minutes: 240,
    vibe_tags: ["adventurous", "active", "romantic"],
    quick_filters: ["active", "romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["sunset hike", "mountain trail", "summit hike"],
    venue_type: null,
    reservation_platforms: ["nps", "recreation_gov", "google_maps"]
  },
  {
    title: "Forest Picnic Adventure",
    description: "Pack a gourmet picnic and hike to a scenic spot in the forest. Set up a blanket and enjoy your meal surrounded by nature.",
    category: "outdoor",
    setting_type: "mountain",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["romantic", "adventurous", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["forest trail", "picnic spot", "nature preserve"],
    venue_type: null,
    reservation_platforms: ["nps", "recreation_gov", "google_maps"]
  },
  {
    title: "Mountain Stargazing Night",
    description: "High altitude means clearer skies. Bring blankets, find a dark spot, and spend the evening identifying constellations together.",
    category: "outdoor",
    setting_type: "mountain",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 15,
    duration_minutes: 180,
    vibe_tags: ["romantic", "chill", "adventurous"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["stargazing", "dark sky", "astronomy"],
    venue_type: null,
    reservation_platforms: ["darksky", "nps", "google_maps"]
  },
  {
    title: "NPS Night-Sky Program",
    description: "Join a ranger-led night sky program at a nearby national park. Telescopes, expert guides, and pristine dark skies.",
    category: "cultural",
    setting_type: "mountain",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 25,
    duration_minutes: 150,
    vibe_tags: ["cultural", "romantic", "adventurous"],
    quick_filters: ["intellectual", "romantic", "low_budget"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["ranger program", "night sky", "national park astronomy"],
    venue_type: null,
    reservation_platforms: ["nps", "recreation_gov"]
  },
  {
    title: "Campfire Dinner in the Woods",
    description: "Cook dinner over a campfire - whether at a campground or a day-use area. Foil packets, hot dogs, or even gourmet camp cooking.",
    category: "outdoor",
    setting_type: "mountain",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["adventurous", "cozy", "romantic"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian"],
    search_keywords: ["campfire", "day use area", "fire ring"],
    venue_type: null,
    reservation_platforms: ["recreation_gov", "google_maps"]
  },
  {
    title: "Scenic Train Ride",
    description: "Board a scenic railway through the mountains. Enjoy the views from the observation car and the romance of train travel.",
    category: "activity",
    setting_type: "mountain",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 150,
    duration_minutes: 240,
    vibe_tags: ["romantic", "chill", "adventurous"],
    quick_filters: ["romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["scenic railway", "train ride", "mountain railroad"],
    venue_type: "tour",
    reservation_platforms: ["google_maps"]
  },

  // ============================================
  // DESERT (10 ideas)
  // ============================================
  {
    title: "Sunset Desert Drive",
    description: "Take a drive through the desert as the sun sets. The changing colors on the rock formations are spectacular.",
    category: "outdoor",
    setting_type: "desert",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 150,
    vibe_tags: ["romantic", "adventurous", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["scenic drive", "desert road", "sunset viewpoint"],
    venue_type: null,
    reservation_platforms: ["nps", "google_maps"]
  },
  {
    title: "Dark-Sky Stargazing",
    description: "The desert offers some of the darkest skies. Visit a designated dark-sky park and witness the Milky Way in all its glory.",
    category: "outdoor",
    setting_type: "desert",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 25,
    duration_minutes: 180,
    vibe_tags: ["romantic", "adventurous", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["dark sky park", "stargazing desert", "night sky viewing"],
    venue_type: null,
    reservation_platforms: ["darksky", "nps", "google_maps"]
  },
  {
    title: "Night Market Exploration",
    description: "Many desert cities have vibrant night markets. Sample street food, browse crafts, and enjoy the cooler evening temperatures.",
    category: "activity",
    setting_type: "desert",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 60,
    duration_minutes: 150,
    vibe_tags: ["fun", "social", "foodie"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["night market", "street market", "evening market"],
    venue_type: null,
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Botanical Garden Sunset",
    description: "Visit a desert botanical garden in the late afternoon. The cacti and succulents look incredible in golden hour light.",
    category: "cultural",
    setting_type: "desert",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 35,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "cultural"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["botanical garden", "desert garden", "cactus garden"],
    venue_type: "museum",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Southwest Cooking Class",
    description: "Learn to make authentic Southwest cuisine together - tamales, green chile, or Navajo tacos.",
    category: "creative",
    setting_type: "desert",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 60,
    estimated_cost_max: 120,
    duration_minutes: 180,
    vibe_tags: ["creative", "foodie", "fun"],
    quick_filters: ["creative"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "gluten-free"],
    search_keywords: ["cooking class", "Southwest cuisine", "Mexican cooking"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "yelp"]
  },
  {
    title: "Art Walk in a Gallery District",
    description: "Explore a desert town's art scene with an evening gallery walk. Many have openings with wine and small bites.",
    category: "cultural",
    setting_type: "desert",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 30,
    duration_minutes: 150,
    vibe_tags: ["cultural", "creative", "romantic"],
    quick_filters: ["intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["art walk", "gallery district", "first friday"],
    venue_type: "gallery",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Desert Sunrise Coffee",
    description: "Wake up before dawn, pack coffee, and drive to a viewpoint to watch the sunrise paint the desert landscape.",
    category: "outdoor",
    setting_type: "desert",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 5,
    estimated_cost_max: 15,
    duration_minutes: 120,
    vibe_tags: ["romantic", "adventurous", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["sunrise viewpoint", "desert overlook", "morning hike"],
    venue_type: null,
    reservation_platforms: ["nps", "google_maps"]
  },
  {
    title: "Historic Southwest Town Tour",
    description: "Explore a historic desert town - ghost town, mining town, or Old West main street. Many have quirky museums and shops.",
    category: "cultural",
    setting_type: "desert",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 40,
    duration_minutes: 180,
    vibe_tags: ["cultural", "adventurous", "fun"],
    quick_filters: ["intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["ghost town", "historic town", "old west town"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Desert Spa Night",
    description: "Book treatments at a desert spa. Many feature mineral pools, outdoor treatments, and stunning views of the landscape.",
    category: "relaxation",
    setting_type: "desert",
    intensity_level: 1,
    cost_level: 3,
    estimated_cost_min: 100,
    estimated_cost_max: 300,
    duration_minutes: 180,
    vibe_tags: ["relaxing", "romantic", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["desert spa", "resort spa", "mineral spa"],
    venue_type: "spa",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Drive-In Under the Stars",
    description: "Desert drive-ins are extra special with clear skies above. Double-feature and unlimited stars.",
    category: "entertainment",
    setting_type: "desert",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 40,
    duration_minutes: 240,
    vibe_tags: ["romantic", "chill", "fun"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["drive-in theater", "outdoor movie", "drive-in cinema"],
    venue_type: "entertainment",
    reservation_platforms: ["google_maps"]
  },

  // ============================================
  // COUNTRYSIDE (10 ideas)
  // ============================================
  {
    title: "Farm-to-Table Dinner",
    description: "Book a farm dinner experience where the meal is served right where the ingredients were grown. Pure, fresh flavors.",
    category: "restaurant",
    setting_type: "countryside",
    intensity_level: 2,
    cost_level: 3,
    estimated_cost_min: 80,
    estimated_cost_max: 200,
    duration_minutes: 180,
    vibe_tags: ["romantic", "foodie", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["farm dinner", "farm to table", "countryside dining"],
    venue_type: "restaurant",
    reservation_platforms: ["airbnb_experiences", "eventbrite", "yelp"]
  },
  {
    title: "Winery or Vineyard Tasting",
    description: "Spend an afternoon visiting a winery. Tour the grounds, learn about the process, and sample wines in a beautiful setting.",
    category: "activity",
    setting_type: "countryside",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 100,
    duration_minutes: 180,
    vibe_tags: ["romantic", "fancy", "chill"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["winery tour", "wine tasting", "vineyard"],
    venue_type: "winery",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Barn Dance or Country Event",
    description: "Find a barn dance, country hoedown, or harvest festival. Learn to line dance and embrace country charm together.",
    category: "entertainment",
    setting_type: "countryside",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 20,
    estimated_cost_max: 60,
    duration_minutes: 180,
    vibe_tags: ["fun", "active", "social"],
    quick_filters: ["fun_silly", "active"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["fall"],
    dietary_friendly: [],
    search_keywords: ["barn dance", "country dance", "harvest festival"],
    venue_type: "event",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Antique Store Challenge",
    description: "Set a small budget and see who can find the most interesting antique or vintage item. Share stories about your finds over lunch.",
    category: "activity",
    setting_type: "countryside",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 60,
    duration_minutes: 180,
    vibe_tags: ["fun", "creative", "chill"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["antique store", "vintage shop", "flea market"],
    venue_type: "retail",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Sunset Field Walk",
    description: "Find a country road or field path and walk as the sun sets. Simple, quiet, and incredibly romantic.",
    category: "outdoor",
    setting_type: "countryside",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 10,
    duration_minutes: 90,
    vibe_tags: ["romantic", "chill", "relaxing"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["country walk", "rural trail", "farm road"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "County Fair Date",
    description: "Corn dogs, ferris wheels, pig races, and funnel cakes. Embrace the classic American county fair experience together.",
    category: "entertainment",
    setting_type: "countryside",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 240,
    vibe_tags: ["fun", "social", "adventurous"],
    quick_filters: ["fun_silly"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["county fair", "state fair", "agricultural fair"],
    venue_type: "event",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Scenic Bike Ride",
    description: "Rent bikes and ride through the countryside on quiet roads or a rail trail. Stop for a picnic lunch halfway.",
    category: "activity",
    setting_type: "countryside",
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["active", "adventurous", "romantic"],
    quick_filters: ["active", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["bike rental", "bike trail", "rail trail"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Glamping Weekend",
    description: "Book a glamping tent or yurt in the countryside. Campfire vibes with comfortable beds and maybe even WiFi.",
    category: "activity",
    setting_type: "countryside",
    intensity_level: 4,
    cost_level: 3,
    estimated_cost_min: 150,
    estimated_cost_max: 350,
    duration_minutes: 2880,
    vibe_tags: ["romantic", "adventurous", "cozy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["glamping", "yurt rental", "luxury camping"],
    venue_type: "lodging",
    reservation_platforms: ["airbnb_experiences", "recreation_gov"]
  },
  {
    title: "Homemade Cook-Off",
    description: "Stop at a farm stand for fresh ingredients, then head home and have a cook-off. Each person makes a dish with what you bought.",
    category: "creative",
    setting_type: "countryside",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 25,
    estimated_cost_max: 60,
    duration_minutes: 180,
    vibe_tags: ["creative", "fun", "foodie"],
    quick_filters: ["creative", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["farm stand", "farmers market", "local produce"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "DIY Outdoor Movie Night",
    description: "Set up a projector in a backyard or field. Hang a sheet, bring blankets, and project a movie under the country stars.",
    category: "entertainment",
    setting_type: "countryside",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 30,
    duration_minutes: 180,
    vibe_tags: ["romantic", "cozy", "creative"],
    quick_filters: ["romantic", "low_budget", "creative"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: [],
    search_keywords: ["outdoor movie", "backyard cinema", "projector"],
    venue_type: null,
    reservation_platforms: []
  },

  // ============================================
  // TROPICAL (10 ideas)
  // ============================================
  {
    title: "Beach Picnic at Sunset",
    description: "Pack tropical fruits, cheese, and champagne for a romantic picnic on the beach as the sun sets over the water.",
    category: "outdoor",
    setting_type: "tropical",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 150,
    vibe_tags: ["romantic", "chill", "relaxing"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["beach picnic", "sunset beach", "oceanfront"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Snorkel Tour",
    description: "Book a snorkel tour to explore coral reefs together. Swim with tropical fish and discover an underwater world.",
    category: "activity",
    setting_type: "tropical",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 120,
    duration_minutes: 180,
    vibe_tags: ["adventurous", "active", "fun"],
    quick_filters: ["active"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["snorkel tour", "reef snorkeling", "ocean tour"],
    venue_type: "tour",
    reservation_platforms: ["airbnb_experiences", "yelp"]
  },
  {
    title: "Salsa or Bachata Dance Class",
    description: "Take a beginner's Latin dance class together. Learn the basics, laugh at your mistakes, and hold each other close.",
    category: "activity",
    setting_type: "tropical",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 70,
    duration_minutes: 90,
    vibe_tags: ["romantic", "active", "fun"],
    quick_filters: ["active", "romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["salsa class", "bachata class", "dance lesson"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "meetup", "yelp"]
  },
  {
    title: "Rooftop Tropical Mocktails",
    description: "Find a rooftop bar with ocean views. Order virgin pina coladas or fresh fruit drinks and watch the clouds drift by.",
    category: "entertainment",
    setting_type: "tropical",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 25,
    estimated_cost_max: 60,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "fancy"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["rooftop bar", "tropical drinks", "ocean view bar"],
    venue_type: "bar",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Night Market Food Crawl",
    description: "Explore a local night market together. Sample street food, try new flavors, and soak up the lively atmosphere.",
    category: "activity",
    setting_type: "tropical",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 150,
    vibe_tags: ["foodie", "fun", "adventurous"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["night market", "street food", "food stalls"],
    venue_type: null,
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Sunrise Paddleboard",
    description: "Rent paddleboards and hit the calm morning waters as the sun rises. Peaceful, beautiful, and a great workout.",
    category: "activity",
    setting_type: "tropical",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["active", "adventurous", "romantic"],
    quick_filters: ["active", "romantic"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["paddleboard rental", "SUP", "sunrise paddleboard"],
    venue_type: "outdoor",
    reservation_platforms: ["airbnb_experiences", "yelp"]
  },
  {
    title: "Couples Massage by the Beach",
    description: "Book a side-by-side massage with ocean sounds in the background. Pure relaxation in paradise.",
    category: "relaxation",
    setting_type: "tropical",
    intensity_level: 1,
    cost_level: 3,
    estimated_cost_min: 150,
    estimated_cost_max: 300,
    duration_minutes: 90,
    vibe_tags: ["romantic", "relaxing", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["couples massage", "beach spa", "resort spa"],
    venue_type: "spa",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Cultural Dance or Luau",
    description: "Attend a traditional cultural show - hula, fire dancing, or a full luau with food and entertainment.",
    category: "entertainment",
    setting_type: "tropical",
    intensity_level: 1,
    cost_level: 3,
    estimated_cost_min: 80,
    estimated_cost_max: 180,
    duration_minutes: 180,
    vibe_tags: ["cultural", "fun", "social"],
    quick_filters: ["intellectual"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian"],
    search_keywords: ["luau", "hula show", "cultural performance"],
    venue_type: "event",
    reservation_platforms: ["airbnb_experiences", "eventbrite"]
  },
  {
    title: "Tropical Cooking Class",
    description: "Learn to make local dishes together - ceviche, poke bowls, or tropical desserts with fresh ingredients.",
    category: "creative",
    setting_type: "tropical",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 60,
    estimated_cost_max: 120,
    duration_minutes: 180,
    vibe_tags: ["creative", "foodie", "fun"],
    quick_filters: ["creative"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["cooking class", "local cuisine", "tropical cooking"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "yelp"]
  },
  {
    title: "No-Plan Exploration Day",
    description: "Pick a direction and just go. Stop at whatever catches your eye - roadside stands, hidden beaches, local spots.",
    category: "activity",
    setting_type: "tropical",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 80,
    duration_minutes: 360,
    vibe_tags: ["adventurous", "fun", "chill"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["road trip", "scenic drive", "exploration"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },

  // ============================================
  // COLD WEATHER (10 ideas)
  // ============================================
  {
    title: "Hot Chocolate Flight",
    description: "Find a cafe that offers different hot chocolate varieties. Sample dark, milk, white, and specialty flavors together.",
    category: "restaurant",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 35,
    duration_minutes: 90,
    vibe_tags: ["cozy", "romantic", "chill"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["fall", "winter"],
    dietary_friendly: ["vegetarian"],
    search_keywords: ["hot chocolate cafe", "cocoa bar", "chocolate shop"],
    venue_type: "cafe",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Ice Skating Date",
    description: "Hit the ice rink - indoor or outdoor. Hold hands, help each other balance, and warm up with cocoa after.",
    category: "activity",
    setting_type: "cold_weather",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 25,
    estimated_cost_max: 50,
    duration_minutes: 120,
    vibe_tags: ["romantic", "active", "fun"],
    quick_filters: ["active", "romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["ice skating", "ice rink", "skating rink"],
    venue_type: "entertainment",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Cozy Fireplace Dinner",
    description: "Book a restaurant with a fireplace. Order comfort food, stay awhile, and let the warmth and glow set the mood.",
    category: "restaurant",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 60,
    estimated_cost_max: 120,
    duration_minutes: 120,
    vibe_tags: ["romantic", "cozy", "fancy"],
    quick_filters: ["romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: ["fall", "winter"],
    dietary_friendly: ["vegetarian", "gluten-free"],
    search_keywords: ["fireplace restaurant", "cozy dining", "winter restaurant"],
    venue_type: "restaurant",
    reservation_platforms: ["opentable", "resy", "yelp"]
  },
  {
    title: "Winter Wonderland Hike",
    description: "Bundle up and hit a snow-covered trail. The quiet of a winter forest is magical, and the views are stunning.",
    category: "outdoor",
    setting_type: "cold_weather",
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 20,
    duration_minutes: 180,
    vibe_tags: ["adventurous", "active", "romantic"],
    quick_filters: ["active", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["winter hiking", "snow trail", "winter walk"],
    venue_type: null,
    reservation_platforms: ["nps", "recreation_gov", "google_maps"]
  },
  {
    title: "Ski Lodge Relaxation",
    description: "Spend the day at a ski lodge - even if you don't ski. Sit by the fire, enjoy the mountain views, and sip warm drinks.",
    category: "relaxation",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 100,
    duration_minutes: 240,
    vibe_tags: ["romantic", "cozy", "chill"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["ski lodge", "mountain lodge", "alpine lodge"],
    venue_type: "lodging",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Cabin Puzzle Night",
    description: "Rent a cabin or stay in for the evening. Tackle a challenging puzzle together with snacks and background music.",
    category: "activity",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 240,
    vibe_tags: ["cozy", "chill", "romantic"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["jigsaw puzzle", "puzzle night", "cozy night in"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Fondue Night",
    description: "Find a fondue restaurant or make it at home. Cheese fondue, chocolate fondue, or both - dip and enjoy.",
    category: "restaurant",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 120,
    duration_minutes: 150,
    vibe_tags: ["romantic", "foodie", "cozy"],
    quick_filters: ["romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: ["fall", "winter"],
    dietary_friendly: ["vegetarian"],
    search_keywords: ["fondue restaurant", "cheese fondue", "chocolate fondue"],
    venue_type: "restaurant",
    reservation_platforms: ["opentable", "yelp"]
  },
  {
    title: "Indoor Garden or Conservatory",
    description: "Escape the cold in an indoor botanical garden or conservatory. Warm, green, and surprisingly romantic.",
    category: "cultural",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "cultural"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["conservatory", "indoor garden", "botanical garden"],
    venue_type: "museum",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Baking Night Together",
    description: "Pick a recipe you've never tried and bake together. Cookies, bread, or an elaborate cake - the mess is part of the fun.",
    category: "creative",
    setting_type: "cold_weather",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 40,
    duration_minutes: 180,
    vibe_tags: ["creative", "cozy", "fun"],
    quick_filters: ["creative", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian"],
    search_keywords: ["baking recipe", "home baking", "cooking together"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Bookstore + Candle Shop Afternoon",
    description: "Browse a cozy bookstore, then visit a candle shop to smell all the winter scents. End with hot drinks somewhere warm.",
    category: "activity",
    setting_type: "cold_weather",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 60,
    duration_minutes: 150,
    vibe_tags: ["cozy", "chill", "romantic"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["bookstore", "candle shop", "cozy shopping"],
    venue_type: "retail",
    reservation_platforms: ["yelp", "google_maps"]
  },

  // ============================================
  // INDOOR ONLY (10 ideas)
  // ============================================
  {
    title: "Cooking Class",
    description: "Take a hands-on cooking class together. Learn to make pasta, sushi, or French pastries from a professional chef.",
    category: "creative",
    setting_type: "indoor_only",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 60,
    estimated_cost_max: 150,
    duration_minutes: 180,
    vibe_tags: ["creative", "foodie", "fun"],
    quick_filters: ["creative"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["cooking class", "culinary class", "chef class"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "yelp"]
  },
  {
    title: "Pottery or Ceramics Class",
    description: "Get your hands dirty at a pottery class. Make bowls, mugs, or sculptures - bonus if they let you glaze and keep them.",
    category: "creative",
    setting_type: "indoor_only",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 100,
    duration_minutes: 150,
    vibe_tags: ["creative", "romantic", "chill"],
    quick_filters: ["creative", "romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["pottery class", "ceramics class", "clay studio"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "meetup", "yelp"]
  },
  {
    title: "Escape Room Challenge",
    description: "Work together to solve puzzles and escape before time runs out. Great teamwork test and tons of fun.",
    category: "activity",
    setting_type: "indoor_only",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 100,
    duration_minutes: 90,
    vibe_tags: ["fun", "adventurous", "social"],
    quick_filters: ["fun_silly", "intellectual"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["escape room", "puzzle room", "escape game"],
    venue_type: "entertainment",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Indoor Rock Climbing",
    description: "Try indoor rock climbing at a bouldering gym. Belay each other, cheer each other on, and build trust (and muscles).",
    category: "activity",
    setting_type: "indoor_only",
    intensity_level: 3,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 150,
    vibe_tags: ["active", "adventurous", "fun"],
    quick_filters: ["active"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["rock climbing gym", "bouldering", "climbing wall"],
    venue_type: "gym",
    reservation_platforms: ["yelp", "google_maps"]
  },
  {
    title: "Paint and Sip Night",
    description: "Join a guided painting class with wine (or mocktails). No artistic skills required - just follow along and have fun.",
    category: "creative",
    setting_type: "indoor_only",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 150,
    vibe_tags: ["creative", "fun", "romantic"],
    quick_filters: ["creative", "romantic"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["paint and sip", "wine and paint", "painting class"],
    venue_type: "class",
    reservation_platforms: ["eventbrite", "yelp"]
  },
  {
    title: "Aquarium After Dark",
    description: "Some aquariums offer evening events with cocktails and fewer crowds. See the sea life in a whole new light.",
    category: "cultural",
    setting_type: "indoor_only",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 80,
    duration_minutes: 180,
    vibe_tags: ["romantic", "cultural", "chill"],
    quick_filters: ["romantic", "intellectual"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["aquarium night", "aquarium event", "evening aquarium"],
    venue_type: "museum",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Science Center or Planetarium",
    description: "Explore interactive exhibits at a science center or catch a planetarium show. Learn something new together.",
    category: "cultural",
    setting_type: "indoor_only",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 60,
    duration_minutes: 180,
    vibe_tags: ["fun", "cultural", "chill"],
    quick_filters: ["intellectual"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["science center", "planetarium", "science museum"],
    venue_type: "museum",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Wine and Cheese Pairing Class",
    description: "Learn from a sommelier which wines pair best with which cheeses. Taste, sip, and discover new favorites.",
    category: "creative",
    setting_type: "indoor_only",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 100,
    duration_minutes: 120,
    vibe_tags: ["romantic", "foodie", "fancy"],
    quick_filters: ["romantic", "luxury"],
    requires_reservation: true,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian"],
    search_keywords: ["wine tasting", "cheese pairing", "wine class"],
    venue_type: "class",
    reservation_platforms: ["airbnb_experiences", "eventbrite", "yelp"]
  },
  {
    title: "Movie Marathon Theme Night",
    description: "Pick a movie series or director and have a marathon. Make themed snacks to match the films.",
    category: "entertainment",
    setting_type: "indoor_only",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 40,
    duration_minutes: 360,
    vibe_tags: ["cozy", "chill", "fun"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["movie marathon", "film night", "themed movies"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "DIY Tasting Night",
    description: "Create your own tasting at home - whiskey, craft beer, olive oil, chocolate, or coffee. Rate and discuss together.",
    category: "creative",
    setting_type: "indoor_only",
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 120,
    vibe_tags: ["foodie", "creative", "romantic"],
    quick_filters: ["creative", "romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["tasting flight", "home tasting", "DIY tasting"],
    venue_type: null,
    reservation_platforms: []
  },

  // ============================================
  // AT HOME (10 ideas)
  // ============================================
  {
    title: "Restaurant Night at Home",
    description: "Set the dining room like a restaurant - candles, nice music, printed menus. Cook a multi-course meal together.",
    category: "restaurant",
    setting_type: "at_home",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 40,
    estimated_cost_max: 100,
    duration_minutes: 240,
    vibe_tags: ["romantic", "fancy", "foodie"],
    quick_filters: ["romantic", "creative"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["home cooking", "fancy dinner", "date night cooking"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "International Night",
    description: "Pick a country and go all in - cook their food, play their music, watch a film set there, learn a few phrases.",
    category: "creative",
    setting_type: "at_home",
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 25,
    estimated_cost_max: 60,
    duration_minutes: 240,
    vibe_tags: ["creative", "cultural", "fun"],
    quick_filters: ["creative", "intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["theme night", "cultural dinner", "international cuisine"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Backyard Stargazing",
    description: "Set up blankets in the backyard with hot drinks. Download a stargazing app and try to identify constellations.",
    category: "outdoor",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 15,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "relaxing"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["stargazing", "backyard date", "night sky"],
    venue_type: null,
    reservation_platforms: ["darksky"]
  },
  {
    title: "Memory Lane Night",
    description: "Go through old photos, watch home videos, or revisit places significant to your relationship via Google Street View.",
    category: "activity",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 10,
    duration_minutes: 120,
    vibe_tags: ["romantic", "chill", "cozy"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["memory book", "photo album", "relationship memories"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Home Spa Night",
    description: "Draw a bath, light candles, put on face masks, and give each other massages. Full relaxation mode.",
    category: "relaxation",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 40,
    duration_minutes: 150,
    vibe_tags: ["romantic", "relaxing", "cozy"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["home spa", "spa night", "self care"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "DIY Cocktail Lab",
    description: "Pick 3-4 cocktail recipes you've never tried. Gather ingredients and become at-home mixologists together.",
    category: "creative",
    setting_type: "at_home",
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 80,
    duration_minutes: 150,
    vibe_tags: ["fun", "creative", "foodie"],
    quick_filters: ["creative", "fun_silly"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["cocktail making", "mixology", "home bartending"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Two-Player Game Night",
    description: "Skip the group games - find two-player board games or card games designed for couples. Compete or cooperate.",
    category: "activity",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 30,
    duration_minutes: 180,
    vibe_tags: ["fun", "chill", "cozy"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["two player games", "couples games", "board games"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Indoor Picnic",
    description: "Spread a blanket on the living room floor, pack a picnic basket, and pretend you're in a park.",
    category: "restaurant",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 120,
    vibe_tags: ["romantic", "fun", "cozy"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["indoor picnic", "home picnic", "romantic dinner"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Couples Book Club",
    description: "Read the same book and discuss it chapter by chapter over the week, then finish with a book-themed dinner.",
    category: "activity",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 120,
    vibe_tags: ["chill", "creative", "romantic"],
    quick_filters: ["intellectual", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["book club", "couples reading", "book discussion"],
    venue_type: null,
    reservation_platforms: []
  },
  {
    title: "Dream Trip Planning Night",
    description: "Research and plan your dream vacation together. Look at destinations, create itineraries, and get excited.",
    category: "activity",
    setting_type: "at_home",
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 20,
    duration_minutes: 180,
    vibe_tags: ["romantic", "fun", "adventurous"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: null,
    dietary_friendly: [],
    search_keywords: ["trip planning", "vacation planning", "travel research"],
    venue_type: null,
    reservation_platforms: []
  },

  // ============================================
  // SEASONAL - SPRING (4 ideas)
  // ============================================
  {
    title: "Cherry Blossom Viewing",
    description: "Find a park with blooming cherry blossoms. Pack a light picnic and spend time under the pink canopy.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 40,
    duration_minutes: 150,
    vibe_tags: ["romantic", "chill", "relaxing"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring"],
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["cherry blossoms", "spring flowers", "botanical park"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Farmers Market Morning",
    description: "Walk through a spring farmers market. Buy fresh produce, flowers, and pastries. Cook brunch with your haul.",
    category: "activity",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 60,
    duration_minutes: 150,
    vibe_tags: ["foodie", "chill", "fun"],
    quick_filters: ["low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring", "summer", "fall"],
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["farmers market", "local produce", "spring market"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Garden Center Date",
    description: "Visit a garden center and pick out plants for your space. Whether succulents or tomatoes, grow something together.",
    category: "activity",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 50,
    duration_minutes: 120,
    vibe_tags: ["chill", "creative", "fun"],
    quick_filters: ["creative", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["spring"],
    dietary_friendly: [],
    search_keywords: ["garden center", "nursery", "plant shop"],
    venue_type: "retail",
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Kite Flying Day",
    description: "Buy or make kites and head to an open field or beach. Childlike joy guaranteed.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 120,
    vibe_tags: ["fun", "active", "romantic"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["spring"],
    dietary_friendly: [],
    search_keywords: ["kite flying", "windy park", "open field"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },

  // ============================================
  // SEASONAL - SUMMER (4 ideas)
  // ============================================
  {
    title: "Outdoor Concert or Festival",
    description: "Find a summer concert series, music festival, or outdoor performance. Bring a blanket and dance under the stars.",
    category: "entertainment",
    setting_type: null,
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 150,
    duration_minutes: 240,
    vibe_tags: ["fun", "social", "romantic"],
    quick_filters: ["fun_silly", "romantic"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["summer"],
    dietary_friendly: [],
    search_keywords: ["outdoor concert", "music festival", "summer concert"],
    venue_type: "event",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Swimming Hole Adventure",
    description: "Find a local swimming hole, river, or lake for a refreshing summer dip. Pack snacks and make a day of it.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 25,
    duration_minutes: 240,
    vibe_tags: ["adventurous", "active", "fun"],
    quick_filters: ["active", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["summer"],
    dietary_friendly: [],
    search_keywords: ["swimming hole", "river swimming", "lake swimming"],
    venue_type: null,
    reservation_platforms: ["recreation_gov", "google_maps"]
  },
  {
    title: "Rooftop Movie Screening",
    description: "Many cities host rooftop movie nights in summer. Grab tickets and watch a film with the city skyline as backdrop.",
    category: "entertainment",
    setting_type: null,
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["romantic", "fun", "chill"],
    quick_filters: ["romantic"],
    requires_reservation: true,
    outdoor_only: true,
    seasonal: ["summer"],
    dietary_friendly: [],
    search_keywords: ["rooftop cinema", "outdoor movie", "summer screening"],
    venue_type: "event",
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Ice Cream Shop Hop",
    description: "Plan a route to visit 3-4 local ice cream shops. Share small scoops at each and crown a winner.",
    category: "restaurant",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 35,
    duration_minutes: 120,
    vibe_tags: ["fun", "foodie", "chill"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["summer"],
    dietary_friendly: ["vegetarian"],
    search_keywords: ["ice cream shop", "gelato", "frozen dessert"],
    venue_type: "restaurant",
    reservation_platforms: ["yelp", "google_maps"]
  },

  // ============================================
  // SEASONAL - FALL (4 ideas)
  // ============================================
  {
    title: "Apple Orchard Day",
    description: "Visit an apple orchard for picking. Many have cider donuts, hayrides, and corn mazes too.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 2,
    cost_level: 1,
    estimated_cost_min: 20,
    estimated_cost_max: 50,
    duration_minutes: 180,
    vibe_tags: ["fun", "adventurous", "cozy"],
    quick_filters: ["fun_silly"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["fall"],
    dietary_friendly: ["vegetarian", "vegan"],
    search_keywords: ["apple picking", "apple orchard", "fall farm"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Fall Foliage Drive",
    description: "Take a scenic drive through areas known for fall colors. Stop at overlooks, grab cider, and enjoy the views.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 50,
    duration_minutes: 240,
    vibe_tags: ["romantic", "chill", "adventurous"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["fall"],
    dietary_friendly: [],
    search_keywords: ["fall foliage", "scenic drive", "leaf peeping"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Pumpkin Patch Visit",
    description: "Pick out pumpkins to carve or decorate. Many patches have photo ops, mazes, and seasonal treats.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 15,
    estimated_cost_max: 40,
    duration_minutes: 150,
    vibe_tags: ["fun", "cozy", "romantic"],
    quick_filters: ["fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["fall"],
    dietary_friendly: [],
    search_keywords: ["pumpkin patch", "fall farm", "pumpkin picking"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Haunted House or Hayride",
    description: "Get spooked together at a haunted attraction. Nothing says bonding like screaming and grabbing each other.",
    category: "entertainment",
    setting_type: null,
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 70,
    duration_minutes: 180,
    vibe_tags: ["fun", "adventurous", "social"],
    quick_filters: ["fun_silly"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["fall"],
    dietary_friendly: [],
    search_keywords: ["haunted house", "haunted hayride", "halloween attraction"],
    venue_type: "entertainment",
    reservation_platforms: ["eventbrite", "google_maps"]
  },

  // ============================================
  // SEASONAL - WINTER (4 ideas)
  // ============================================
  {
    title: "Holiday Lights Tour",
    description: "Drive through neighborhoods known for holiday decorations or visit an official lights display.",
    category: "entertainment",
    setting_type: null,
    intensity_level: 1,
    cost_level: 1,
    estimated_cost_min: 10,
    estimated_cost_max: 30,
    duration_minutes: 120,
    vibe_tags: ["romantic", "cozy", "fun"],
    quick_filters: ["romantic", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["holiday lights", "christmas lights", "light display"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "Holiday Market Shopping",
    description: "Browse a festive holiday market for unique gifts, warm drinks, and seasonal treats.",
    category: "activity",
    setting_type: null,
    intensity_level: 1,
    cost_level: 2,
    estimated_cost_min: 30,
    estimated_cost_max: 100,
    duration_minutes: 180,
    vibe_tags: ["cozy", "fun", "social"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["holiday market", "christmas market", "winter market"],
    venue_type: null,
    reservation_platforms: ["eventbrite", "google_maps"]
  },
  {
    title: "Sledding Hill Adventure",
    description: "Find a local sledding hill after a fresh snow. Bring sleds (or improvise!) and embrace your inner kid.",
    category: "outdoor",
    setting_type: null,
    intensity_level: 3,
    cost_level: 1,
    estimated_cost_min: 0,
    estimated_cost_max: 20,
    duration_minutes: 120,
    vibe_tags: ["fun", "active", "adventurous"],
    quick_filters: ["active", "fun_silly", "low_budget"],
    requires_reservation: false,
    outdoor_only: true,
    seasonal: ["winter"],
    dietary_friendly: [],
    search_keywords: ["sledding", "snow tubing", "winter sports"],
    venue_type: null,
    reservation_platforms: ["google_maps"]
  },
  {
    title: "New Year's Eve at Home",
    description: "Skip the crowded bars. Cook a fancy dinner, put on a playlist, and ring in the new year just the two of you.",
    category: "entertainment",
    setting_type: null,
    intensity_level: 2,
    cost_level: 2,
    estimated_cost_min: 50,
    estimated_cost_max: 150,
    duration_minutes: 300,
    vibe_tags: ["romantic", "fancy", "cozy"],
    quick_filters: ["romantic"],
    requires_reservation: false,
    outdoor_only: false,
    seasonal: ["winter"],
    dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
    search_keywords: ["new years eve", "celebration dinner", "holiday dinner"],
    venue_type: null,
    reservation_platforms: []
  },
]

export default dateIdeas
