-- 024: Add a "Romance & Intimacy" set of tasteful, flirty/sensual date ideas for
-- couples (APPLIED 2026-06). Fills a genuine catalog gap (no romance category
-- existed). New taxonomy: category 'romance' (no CHECK constraint on category) and
-- vibe 'flirty' (both added to lib/constants/options.ts so they're selectable +
-- boosted by the v4 scorer's category/vibe terms). Idempotent via NOT EXISTS on
-- title. NOTE: the outdoor_only column was dropped in migration 019, so it is NOT
-- in the column list (unlike migration 015).

INSERT INTO idea_templates (
  title, description, category, cost_level, estimated_cost_min, estimated_cost_max,
  duration_minutes, vibe_tags, requires_reservation, seasonal, dietary_friendly,
  search_keywords, venue_type, setting_type, intensity_level, quick_filters, reservation_platforms
)
SELECT
  title, description, category, cost_level, estimated_cost_min, estimated_cost_max,
  duration_minutes, vibe_tags, requires_reservation, seasonal, dietary_friendly,
  search_keywords, venue_type, setting_type, intensity_level, quick_filters, reservation_platforms
FROM jsonb_to_recordset($dn$[
{"title":"Sensual Massage Night","description":"Dim the lights, warm a bottle of oil, and take turns tracing the day's tension out of each other's shoulders, back, and everywhere else. No phones, no rush — just slow hands and a playlist that makes you both lose track of time.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":25,"duration_minutes":60,"vibe_tags":["romantic","flirty","relaxing","cozy"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["massage oil","couples massage at home","candles"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Candlelit Dinner for Two","description":"Cook one decadent course together, kill the overhead lights, and set the table with every candle you own. Feed each other the first bite, let dinner run long, and see where dessert leads.","category":"romance","cost_level":2,"estimated_cost_min":30,"estimated_cost_max":60,"duration_minutes":120,"vibe_tags":["romantic","flirty","foodie","cozy"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["romantic dinner at home","candlelit","cook together"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Truth or Dare: Date Night Edition","description":"Build a deck of daring questions and playful challenges, pour two drinks, and trade things you've never said out loud. Equal parts giggling and blushing — the dares are where it gets interesting.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":15,"duration_minutes":60,"vibe_tags":["flirty","fun","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples truth or dare","flirty questions","date night game"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Couples' Boudoir Photoshoot","description":"Book a photographer who specializes in tasteful, sultry couples portraits and spend an afternoon being told how good you look together. You'll walk out with prints worth framing and a new way of seeing each other.","category":"romance","cost_level":4,"estimated_cost_min":150,"estimated_cost_max":400,"duration_minutes":120,"vibe_tags":["romantic","flirty","creative","fancy"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples boudoir","intimate photoshoot","photographer"],"venue_type":"studio","setting_type":"indoor_only","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["google_maps","yelp"]},
{"title":"Body Painting Night","description":"Lay down a drop cloth, grab a set of washable paints, and turn each other into the canvas. It starts artistic and ends with a very good reason to share a shower.","category":"romance","cost_level":1,"estimated_cost_min":15,"estimated_cost_max":30,"duration_minutes":90,"vibe_tags":["creative","flirty","fun","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["body paint","washable paint","creative couples"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Strip Poker & Signature Cocktails","description":"Mix two cocktails you've never tried, deal the cards, and play by house rules. Low stakes, high tension — winner's choice for how the night ends.","category":"romance","cost_level":1,"estimated_cost_min":10,"estimated_cost_max":25,"duration_minutes":90,"vibe_tags":["flirty","fun","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["strip poker","cocktails at home","couples card game"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Couples' Spa & Private Soak","description":"Book a side-by-side massage followed by a long soak in a private hot tub or steam room. Arrive tense, leave loose-limbed and in no hurry to put your clothes back on.","category":"romance","cost_level":4,"estimated_cost_min":150,"estimated_cost_max":300,"duration_minutes":150,"vibe_tags":["romantic","relaxing","fancy"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples spa","couples massage","private soak","day spa"],"venue_type":"spa","setting_type":"big_city","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":["yelp","google_maps"]},
{"title":"Lingerie Shopping for Each Other","description":"Wander a boutique together and each pick something for the other to try on — your taste, their reveal. The fitting-room runway show is the whole point.","category":"romance","cost_level":3,"estimated_cost_min":75,"estimated_cost_max":150,"duration_minutes":90,"vibe_tags":["flirty","romantic","fun"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["lingerie boutique","couples shopping"],"venue_type":"boutique","setting_type":"big_city","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"Blindfold Taste Test","description":"One blindfold, a tray of strawberries, chocolate, honey and a good wine, and a simple rule: guess each bite. Feeding each other in the dark turns dessert into the main event.","category":"romance","cost_level":2,"estimated_cost_min":20,"estimated_cost_max":40,"duration_minutes":45,"vibe_tags":["flirty","foodie","romantic","fun"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["blindfold tasting","sensory date","chocolate strawberries"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Slow Dance in the Living Room","description":"Push the coffee table aside, queue up the songs from when you first fell for each other, and sway barefoot with no audience. The kind of ordinary magic that tends to turn into more.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":10,"duration_minutes":45,"vibe_tags":["romantic","cozy","chill"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["slow dance","romantic playlist","at home date"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Burlesque Show Night Out","description":"Dress sharp, split a bottle of something bubbly, and take in a night of feathers, glitter, and confident tease. You'll leave inspired and very ready to head home.","category":"romance","cost_level":3,"estimated_cost_min":75,"estimated_cost_max":140,"duration_minutes":180,"vibe_tags":["flirty","fun","social","fancy"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["burlesque show","cabaret","date night out"],"venue_type":"cabaret","setting_type":"big_city","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["eventbrite","google_maps"]},
{"title":"Hot Springs Soak Under the Stars","description":"Drive out to a natural or resort hot spring, sink in up to your shoulders, and let the steam and the stars do the rest. Bring a flask of cocoa and stay until you're both pruny.","category":"romance","cost_level":3,"estimated_cost_min":60,"estimated_cost_max":130,"duration_minutes":180,"vibe_tags":["romantic","relaxing","adventurous"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["hot springs","natural soak","stargazing"],"venue_type":"hot springs","setting_type":"mountain","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"Write Each Other a Fantasy","description":"Pour two glasses, set a timer, and each write the other a short, steamy 'what if' scene. Read them aloud by candlelight — confessions have never been this fun.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":10,"duration_minutes":60,"vibe_tags":["creative","flirty","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["write a fantasy","romantic writing game","couples"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Sultry Partner Dance Class","description":"Sign up for a bachata or tango lesson and spend an hour learning to move as one — hips, hands, eye contact and all. The closeness translates straight into the rest of the night.","category":"romance","cost_level":2,"estimated_cost_min":30,"estimated_cost_max":60,"duration_minutes":75,"vibe_tags":["romantic","flirty","active","cultural"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["bachata class","tango lesson","couples dance"],"venue_type":"dance studio","setting_type":"big_city","intensity_level":3,"quick_filters":["romantic"],"reservation_platforms":["meetup","eventbrite"]},
{"title":"Midnight Skinny Dip","description":"Find a quiet stretch of warm coast after dark, dare each other in, and float under the stars with the whole place to yourselves. Pack towels and a blanket for after.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":15,"duration_minutes":60,"vibe_tags":["adventurous","flirty","romantic"],"requires_reservation":false,"seasonal":["summer"],"dietary_friendly":[],"search_keywords":["night swim","skinny dip","beach after dark"],"venue_type":"beach","setting_type":"coastal","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Blanket Fort & Movie Night","description":"Build the most ridiculous pillow-and-string-light fort you can, load up snacks and a film neither of you intends to finish, and get tangled up under the blankets.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":20,"duration_minutes":120,"vibe_tags":["cozy","flirty","romantic","chill"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["blanket fort","movie night in","cozy date"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Edible-Treats Tasting","description":"Set out chocolate fondue, honey, whipped cream and fresh fruit, and make a slow, playful game of tasting everything on the spread — and each other.","category":"romance","cost_level":2,"estimated_cost_min":20,"estimated_cost_max":45,"duration_minutes":60,"vibe_tags":["flirty","foodie","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["chocolate fondue","edible treats","sensory tasting"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Couples' Massage Workshop","description":"Take a guided class that teaches you to give each other a proper massage — pressure, oils, technique. The real reward is every night afterward when you put the homework to use.","category":"romance","cost_level":3,"estimated_cost_min":75,"estimated_cost_max":150,"duration_minutes":120,"vibe_tags":["romantic","relaxing","creative"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples massage class","massage workshop","wellness"],"venue_type":"wellness studio","setting_type":"big_city","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["eventbrite","meetup"]}
]$dn$) AS x(
  title text, description text, category text, cost_level int,
  estimated_cost_min int, estimated_cost_max int, duration_minutes int,
  vibe_tags text[], requires_reservation boolean, seasonal text[], dietary_friendly text[],
  search_keywords text[], venue_type text, setting_type text, intensity_level int,
  quick_filters text[], reservation_platforms text[]
)
WHERE NOT EXISTS (SELECT 1 FROM idea_templates t WHERE t.title = x.title);
