-- 025: Expand the "romance" set with 18 bolder, more adventurous date ideas
-- (APPLIED 2026-06) — role-play, sensory/kink-curious play (framed with consent,
-- safe words, and body-safe gear), discreet public thrills, anticipation games and
-- an overnight escape. Tasteful/suggestive, not explicit. Brings the romance
-- category to 36 ideas total (with migration 024). Same taxonomy (category
-- 'romance', vibe 'flirty'); idempotent via NOT EXISTS on title; outdoor_only is
-- intentionally absent (dropped in migration 019).

INSERT INTO idea_templates (
  title, description, category, cost_level, estimated_cost_min, estimated_cost_max,
  duration_minutes, vibe_tags, requires_reservation, seasonal, dietary_friendly,
  search_keywords, venue_type, setting_type, intensity_level, quick_filters, reservation_platforms
)
SELECT
  title, description, category, cost_level, estimated_cost_min, estimated_cost_max,
  duration_minutes, vibe_tags, requires_reservation, seasonal, dietary_friendly,
  search_keywords, venue_type, setting_type, intensity_level, quick_filters, reservation_platforms
FROM jsonb_to_recordset($dn$[
{"title":"Stranger-at-a-Bar Role-Play","description":"Arrive at the bar separately, invent new names and backstories, and let two 'strangers' flirt their way through the night like it's the first time all over again. The hard part is keeping a straight face; the fun part is taking the stranger home.","category":"romance","cost_level":2,"estimated_cost_min":30,"estimated_cost_max":60,"duration_minutes":120,"vibe_tags":["flirty","fun","romantic","social"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["role play date","meet as strangers","cocktail bar"],"venue_type":"bar","setting_type":"big_city","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["google_maps","yelp"]},
{"title":"Fantasy Swap Night","description":"Each of you writes a fantasy or role-play scenario on a slip, drop them in a jar, and draw one to bring to life tonight. No judgment, just curiosity — you might learn something new about each other.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":15,"duration_minutes":90,"vibe_tags":["flirty","creative","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["fantasy jar","role play ideas","couples"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Sensate Focus Exercise","description":"Borrow sex therapy's go-to intimacy exercise: take turns slowly touching each other with no goal and no rush — bare hands, warm oil, a feather — paying attention only to how each sensation feels. Taking 'performance' off the table is exactly what lets the heat build.","category":"romance","cost_level":1,"estimated_cost_min":10,"estimated_cost_max":30,"duration_minutes":60,"vibe_tags":["romantic","relaxing","flirty","creative"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["sensate focus","mindful touch","sensual massage"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Sensory Exploration Night","description":"Blindfold one of you, then explore with a feather, an ice cube, a swatch of silk, and a little warm oil — narrating nothing, letting touch do the talking. Switch when they can't take any more anticipation.","category":"romance","cost_level":1,"estimated_cost_min":10,"estimated_cost_max":30,"duration_minutes":60,"vibe_tags":["flirty","romantic","creative","relaxing"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["sensory play","blindfold","feather and ice"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Silk-Tie Trust Game","description":"Agree on a safe word first, then let one of you loosely tie the other's wrists with a silk scarf and tease at an unhurried pace. It's less about the restraint than the trust — and the wait.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":20,"duration_minutes":60,"vibe_tags":["flirty","romantic","adventurous"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["silk tie","light restraint","trust game","safe word"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Warm Wax Massage","description":"Light a body-safe, low-temperature massage candle, let it melt into warm oil, and drizzle it slowly along bare skin before working it in with your hands. Equal parts spa night and slow seduction.","category":"romance","cost_level":1,"estimated_cost_min":15,"estimated_cost_max":35,"duration_minutes":60,"vibe_tags":["flirty","romantic","relaxing"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["massage candle","low temp wax","sensual massage"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Tantra & Breathwork for Two","description":"Sit knee to knee, breathe in sync, and hold each other's gaze far longer than feels comfortable — until it stops being awkward and starts being electric. A slow on-ramp to a very connected night.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":20,"duration_minutes":75,"vibe_tags":["romantic","relaxing","creative"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["tantra","breathwork","eye gazing","couples connection"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Flirty Scavenger Hunt","description":"Hide a trail of teasing notes around the place, each clue a little bolder than the last, all leading to a final 'prize' you've set up in the bedroom. Make them work for it.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":20,"duration_minutes":90,"vibe_tags":["flirty","fun","creative","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["scavenger hunt","love notes","clue trail"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Back-Row Late-Show Make-Out","description":"Buy tickets to the last showing on a quiet weeknight, claim the back row, and rediscover how much fun a movie you barely watch can be. Popcorn optional.","category":"romance","cost_level":2,"estimated_cost_min":25,"estimated_cost_max":45,"duration_minutes":150,"vibe_tags":["flirty","fun","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["late movie","back row","cinema date"],"venue_type":"cinema","setting_type":"big_city","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"Steam-the-Windows Lookout Drive","description":"Drive out to a scenic overlook after dark, kill the engine, and let it turn into the kind of parked-car night you thought you'd aged out of. Bring a blanket and a good playlist.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":20,"duration_minutes":90,"vibe_tags":["flirty","romantic","adventurous"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["scenic overlook","lovers lane","night drive"],"venue_type":"scenic overlook","setting_type":"coastal","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"Under-the-Table Teasing Dinner","description":"Book a nice restaurant, then play a slow, discreet game of footsie and whispered dares between courses. Whoever cracks first is in charge of dessert back home.","category":"romance","cost_level":3,"estimated_cost_min":75,"estimated_cost_max":150,"duration_minutes":120,"vibe_tags":["flirty","romantic","foodie","fancy"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["fancy dinner","teasing game","date night out"],"venue_type":"restaurant","setting_type":"big_city","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["opentable","resy"]},
{"title":"No-Agenda Hotel Staycation","description":"Book a hotel room in your own city, hang the do-not-disturb sign, and disappear for the night — room service, robes, a deep tub, and absolutely nowhere to be. The novelty of a new room does the rest.","category":"romance","cost_level":4,"estimated_cost_min":150,"estimated_cost_max":350,"duration_minutes":480,"vibe_tags":["romantic","fancy","flirty","relaxing"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["hotel staycation","romantic getaway","do not disturb"],"venue_type":"hotel","setting_type":"big_city","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"Couples' Pole & Aerial Class","description":"Take a beginner pole or aerial class together, laugh through the wobbles, and discover muscles — and confidence — you didn't know you had. Practice the moves later, audience of one.","category":"romance","cost_level":2,"estimated_cost_min":40,"estimated_cost_max":70,"duration_minutes":75,"vibe_tags":["flirty","active","creative","adventurous"],"requires_reservation":true,"seasonal":null,"dietary_friendly":[],"search_keywords":["pole class","aerial class","couples fitness"],"venue_type":"studio","setting_type":"big_city","intensity_level":3,"quick_filters":["romantic"],"reservation_platforms":["eventbrite","meetup"]},
{"title":"Browse a Tasteful Pleasure Boutique","description":"Wander a well-reviewed, welcoming boutique together with an open mind and pick out one new thing to try — no pressure, all curiosity. Half the fun is the conversation on the way home.","category":"romance","cost_level":2,"estimated_cost_min":30,"estimated_cost_max":80,"duration_minutes":60,"vibe_tags":["flirty","fun","adventurous"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples boutique","pick something new","date shopping"],"venue_type":"boutique","setting_type":"big_city","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":["google_maps"]},
{"title":"All-Day Anticipation","description":"Set a few playful ground rules over morning coffee, then build the tension by text all day — hints, dares, countdowns — until you finally reunite at the door. Slow burn, big payoff.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":10,"duration_minutes":60,"vibe_tags":["flirty","fun","romantic"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["anticipation","slow burn","texting game"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Candlelit Mirror Night","description":"Clear the bedroom, light a dozen candles, prop up a mirror, and slow-dance out of your clothes while watching the two of you from a whole new angle. Confidence looks good on you both.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":25,"duration_minutes":60,"vibe_tags":["flirty","romantic","creative"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["mirror","candlelight","slow dance"],"venue_type":"home","setting_type":"at_home","intensity_level":2,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Couples' Bath Ritual","description":"Run a deep bath with oils, petals, and candlelight, pour two glasses of something cold, and take turns washing each other with zero rush. The ultimate reset before an unhurried night.","category":"romance","cost_level":1,"estimated_cost_min":10,"estimated_cost_max":30,"duration_minutes":60,"vibe_tags":["romantic","relaxing","cozy"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["couples bath","bath oils","candlelit soak"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]},
{"title":"Yes, No, Maybe Desires List","description":"Each fill out the same list of things you might try in the bedroom, marking every item Yes, No, or Maybe on your own — then compare. Only the overlaps are on the table, so it becomes a pressure-free, honest map of where to explore next. The best kind of homework.","category":"romance","cost_level":1,"estimated_cost_min":0,"estimated_cost_max":10,"duration_minutes":60,"vibe_tags":["flirty","romantic","creative","adventurous"],"requires_reservation":false,"seasonal":null,"dietary_friendly":[],"search_keywords":["yes no maybe list","desires checklist","explore boundaries"],"venue_type":"home","setting_type":"at_home","intensity_level":1,"quick_filters":["romantic"],"reservation_platforms":[]}
]$dn$) AS x(
  title text, description text, category text, cost_level int,
  estimated_cost_min int, estimated_cost_max int, duration_minutes int,
  vibe_tags text[], requires_reservation boolean, seasonal text[], dietary_friendly text[],
  search_keywords text[], venue_type text, setting_type text, intensity_level int,
  quick_filters text[], reservation_platforms text[]
)
WHERE NOT EXISTS (SELECT 1 FROM idea_templates t WHERE t.title = x.title);
